### ISSUE TITLE
It's easy to make learn the image recognition of your project?

### ISSUE THREAD

**Issue by davidmartinezros** [grolex18/tensorboot#1]
Hi,

I make works your project in my server and it works fine.

But I saw on google fotos, that the google system learn when you use it.

It's possible to make your project learns? For example, if the label is not find, the user is using the app can propourse a label to identify the image.

What I have to do to make this?

Thanks in advanced,

David

**Comment by grolex18** [comment]
Hi David,
A simple and robust way is to collect new data provided by users and retrain your NN periodically using old and new data.
Check this for details: 
https://en.wikipedia.org/wiki/Online_machine_learning
https://medium.com/value-stream-design/online-machine-learning-515556ff72c5
